DZ2
maxapon/ReactCourse pull request #2
Opened 2024-07-03 13:56 UTC by maxapon

2024-07-03 15:30 UTC, zubkov7 commented on src/components/app/component.jsx
> +    const [currentId, setId] = React.useState(restaurants[0].id);
обычно импортируют import { useState } from "react"
так код чище выглядит

2024-07-03 15:34 UTC, zubkov7 requested changes

2024-07-03 15:34 UTC, zubkov7 commented on src/components/app/component.jsx
> +        Array.from(document.getElementsByClassName("tabBtn")).forEach((element) => {
в реакте мы не взаимодействуем с элементами таким способом

можно при рендере делать проверку ниже restaurant.id === currentId и делать необходимые действия

2024-07-03 15:34 UTC, zubkov7 commented on src/components/app/component.jsx
> +    const [currentId, setId] = React.useState(restaurants[0].id);
по неймингу обычно используется [**state**, set**State**]

в вашем кейсе получается [**currentId**, set**СurrentId**]

лучше еще подсветить, что это именно айди ресторана

2024-07-03 15:34 UTC, zubkov7 commented on src/components/app/component.jsx
> +                {restaurants.map((restaurant) => (
нам нужно рендерит только активный ресторан

можно использовать метод массива restaurants.find и отображать необходимый ресторан

2024-07-07 09:36 UTC, zubkov7 commented on src/components/app/component.jsx
> +                {restaurants.map((restaurant) => (
у map вторым параметром можно достать индекс - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2024-07-07 09:37 UTC, zubkov7 commented on src/components/app/component.jsx
> +                    <button className={restaurants.indexOf(restaurant) == currRestaurantIndx ? "tabBtn active" : "tabBtn"}
всегда правильнее использовать строгое сравнение ===

2024-07-07 09:38 UTC, zubkov7 commented on src/components/app/component.jsx
> +    const [currRestaurantIndx, setCurrRestaurantIndx] = useState(0);
по условии необходимо по умолчанию отображать первый ресторан

2024-07-07 20:29 UTC, maxapon commented on src/components/app/component.jsx
> +    const [currRestaurantIndx, setCurrRestaurantIndx] = useState(0);
По умолчанию у меня и отображается 1 в списке ресторан. Не понял, что именно нужно поменять?

2024-07-07 20:41 UTC, zubkov7 commented on src/components/app/component.jsx
> +    const [currRestaurantIndx, setCurrRestaurantIndx] = useState(0);
сори )) между ДЗ запутался просто, кто-то использует индекс, а кто-то сущность ресторана именно

с индексом тут ок

2024-07-07 20:55 UTC, maxapon commented on src/components/app/component.jsx
> +    const [currRestaurantIndx, setCurrRestaurantIndx] = useState(0);
понял, хорошо))

2024-07-08 07:09 UTC, zubkov7 commented on src/components/counter/component.jsx
> +    }, [])
в колбеках не указаны необходимые зависимости, при изменении max, там будет лежать старое значение

прогоните pnpm run lint, это должно подсветить проблему. Еще нужно настроить плагин eslint для ide, он сразу подсветит

2024-07-08 07:11 UTC, zubkov7 commented on src/components/review-form/component.jsx
> +                <Counter initValue={form.rating} onChange={(event) => {dispatch({type: "setRating", payload: event.target.value})}}/>
мы можем переиспользовать компонент Counter, немного переписав его, чтобы он принимал increment, decrement, value
В useForm поддержать необходимые actions

2024-07-08 07:12 UTC, zubkov7 commented
прогоните еще prettier пожалуйста, чтобы отформатировать код

2024-07-16 18:50 UTC, merged