DZ8
maxapon/ReactCourse pull request #6
Opened 2024-07-26 21:47 UTC by maxapon

2024-07-28 09:35 UTC, zubkov7 requested changes

2024-07-28 09:35 UTC, zubkov7 commented on src/components/app-content/container.jsx
> +  var restIds = [];
на каждом ререндере restIds будет сбрасываться на [] и заново задаваться. В подходе с rtk query можно передавать полностью сущность, либо делать selectFromResult, чтобы получить только айдишники

плюс var лучше никогда не использовать, у нее есть ряд неожиданных поведений. Лучше придерживаться let и const при объявлении переменных

2024-07-28 09:35 UTC, zubkov7 commented on src/components/restaurant/container.jsx
> +  const { data: restData, isSuccess: restIsSuccess } =
мы на старте приложения загрузили все данные о ресторанах, в данном кейсе будем перезапрашивать данные для конкретного ресторана, поэтому можем прокидывать ресторан в потребителе, который рисует список

2024-07-28 09:35 UTC, zubkov7 commented on src/redux/index.js
> +        [RestaurantSlice.name]: RestaurantSlice.reducer,
если используем rtk query, то эти редьюсеры уже не нужны

2024-07-28 14:51 UTC, maxapon commented on src/components/restaurant/container.jsx
> +  const { data: restData, isSuccess: restIsSuccess } =
useGetRestaurantByIdQuery возвратит данные по ресторану, но там только ID блюд и отзывов. В моем случае удобнее было получать не отдельные блюда и отзывы по их ID, а разом выгрузить все меню и отзывы с текстом, ингредиентами и названиями. Что я и сделал

2024-07-28 18:02 UTC, zubkov7 commented on src/components/restaurant/container.jsx
> +  const { data: restData, isSuccess: restIsSuccess } =
не очень понял, как загрузка отзывов и меня, связана с лишним запросом данных по конкретному ресторану

запрос useGetRestaurantsQuery уже загрузил данные по всем ресторанам, соответственно из него мы можем получить сущность нужного ресторана

useGetRestaurantByIdQuery сделает отдельный запрос по нужному ресторана, а у нас эти данные уже есть

2024-07-28 18:06 UTC, zubkov7 commented on src/components/app-content/container.jsx
> +    restIds.push(...data.map((item) => item.id));
использовать глобальные переменные не совсем в подходе реакта. Если у вас будет перезапрос useGetRestaurantsQuery, то айдишники останутся старые

поэтому необходимо применить selectFromResult или передавать массив сущностей, а не айдишников в компоненты

2024-07-28 18:06 UTC, zubkov7 commented on src/redux/index.js
> -    [RestaurantSlice.name]: RestaurantSlice.reducer,
сами файлы редьюсеров тоже можно удалить

2024-08-05 08:32 UTC, zubkov7 commented on package.json
> +    "pnpm": "^9.6.0",
pnpm не нужен в зависимостях

2024-08-05 08:34 UTC, zubkov7 commented on src/components/app-content/container.jsx
> +      selectFromResult: ({ data, isError, isFetching, isLoading }) => ({
тут можно { data, ...rest } и возвращать return { ...rest, data }

чтобы не потерять остальные поля

2024-08-05 08:35 UTC, zubkov7 commented on src/components/restaurant-page-content/component.jsx
> +        <div style={{ display: "inline-block", margin: 5 }}>
стили лучше добавлять через css модули с помощью классов

2024-08-05 08:35 UTC, zubkov7 commented on src/components/restaurant-page-link/component.jsx
> +    <>
лишний фрагмент

2024-08-05 08:38 UTC, zubkov7 commented on src/components/review-list/component.jsx
> +            userName={
компонент отзыва может доставать данные из квери useGetUsersQuery, результат возьмет из кеша.

2024-08-05 08:39 UTC, zubkov7 approved these changes

2024-08-05 19:50 UTC, maxapon commented
Исправления в следующем задании добавлю

2024-08-05 19:50 UTC, merged